---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staginginternaltableau
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/whitelist-source-range: "62.25.109.196/32, 80.169.158.34/32, 80.193.85.91/32, 86.188.197.170/29, 52.48.127.150/32, 52.48.127.151/32, 52.48.127.152/32, 52.48.127.153/32, 52.209.62.128/25, 52.56.62.128/25, 35.177.179.157/32, 31.221.110.80/29,195.95.131.0/24,5.148.69.20/32,5.148.32.192/26,193.164.115.0/24,203.63.205.64/28,5.148.32.229/32,119.73.144.40/32,85.211.101.55/32"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"

spec:
  tls:
  - hosts:
    - {{ .URL }}
    secretName: staginginternaltableau-external-tls-cmio
  rules:
  - host: {{ .URL }}
    http:
      paths:
      - backend:
          service:
            name: staginginternaltableau
            port: https
        path: /
